title: Unión Hondureña
email: hndoss@gmail.com
description: >
  Iglesia Adventista del Séptimo Día Movimiento de Reforma - Unión Hondureña
url: "https://argushn.github.io"
baseurl: "/union-website"
# baseurl: ""

## Contact Information
company_name: Unión Hondureña
address_line: J47F+658, Siguatepeque, Comayagua
telephone_number: +504 8777-9224
company_email: asdmruh@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6461.3216771822235!2d-87.87977943336612!3d14.609686376530423!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f65bf202adb95d1%3A0x8b3f64d6e4dbf372!2sEscuela%20misionera%20Eben-Eser!5e0!3m2!1ses-419!2shn!4v1720606045663!5m2!1ses-419!2shn
facebook_link: https://www.facebook.com/profile.php?id=100064555941818
youtube_link: https://www.youtube.com/@unionhondurenaasdmr8339

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  principles:
    output: true
  ministers:
    output: true
